version: '3.8'

services:
  # Dịch vụ Backend API
  apiservice:
    build:
      context: .
      dockerfile: src/TodojsAspire.ApiService/Dockerfile
    container_name: todo_api
    ports:
      - "8081:8080" # Map port 8081 của máy host vào port 8080 của container
    environment:
      # Cung cấp connection string cho SQLite
      - ConnectionStrings__db=Data Source=/app/data/todo.db
    volumes:
      - sqlite_data:/app/data # Gắn volume để lưu trữ file todo.db

  # Dịch vụ Frontend
  frontend:
    build:
      context: src/todo-frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    ports:
      - "8080:80" # Map port 8080 của máy host vào port 80 của container Nginx
    depends_on:
      - apiservice # Khởi động frontend sau khi apiservice đã khởi động

# Định nghĩa volume để lưu dữ liệu SQLite
volumes:
  sqlite_data: